<?php

// TOP SCORE, LEFT SCORE
$players = array(
	array(
		"name"	=>	"Landon",
		"initials"	=>	"LB",
		"squares"	=>	array(
			array(1,3),
			array(8,1),
			array(3,6),
			array(0,2),
			array(0,7),
			array(2,5),
			array(7,7),
			array(6,6),
			array(5,4),
			array(9,7),
			array(9,3),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Amber",
		"initials"	=>	"AP",
		"squares"	=>	array(
			array(1,5),
			array(3,8),
			array(5,2),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Dominic",
		"initials"	=>	"DP",
		"squares"	=>	array(
			array(1,6),
			array(8,0),
			array(4,1),
			array(0,5),
			array(3,4),
			array(2,9),
			array(7,0),
			array(6,8),
			array(5,3),
			array(9,2),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Norman",
		"initials"	=>	"NR",
		"squares"	=>	array(
			array(1,4),
			array(0,0),
			array(2,3),
			array(7,5),
			array(5,7),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Joe",
		"initials"	=>	"JS",
		"squares"	=>	array(
			array(1,1),
			array(8,9),
			array(8,3),
			array(4,3),
			array(0,4),
			array(3,7),
			array(2,6),
			array(7,8),
			array(6,2),
			array(5,5),
			array(9,4),
			array(9,0),
			array(9,9),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Ryan",
		"initials"	=>	"RR",
		"squares"	=>	array(
			array(1,2),
			array(4,6),
			array(4,7),
			array(3,1),
			array(3,0),
			array(2,8),
			array(6,7),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Danny",
		"initials"	=>	"DE",
		"squares"	=>	array(
			array(1,0),
			array(8,5),
			array(4,9),
			array(0,8),
			array(3,3),
			array(2,7),
			array(7,2),
			array(6,4),
			array(5,6),
			array(9,1),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Mike",
		"initials"	=>	"MA",
		"squares"	=>	array(
			array(1,7),
			array(4,0),
			array(0,3),
			array(5,8),
			array(5,9),
			array(2,4),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Shawri",
		"initials"	=>	"SL",
		"squares"	=>	array(
			array(1,9),
			array(4,5),
			array(2,1),
			array(6,3),
			array(9,6),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Larry",
		"initials"	=>	"LC",
		"squares"	=>	array(
			array(1,8),
			array(8,4),
			array(3,2),
			array(7,6),
			array(6,9),
			array(9,5),
			array(9,8),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Jesse",
		"initials"	=>	"JR",
		"squares"	=>	array(
			array(8,6),
			array(8,2),
			array(4,8),
			array(3,9),
			array(6,5),
			array(5,1),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Brandon",
		"initials"	=>	"BS",
		"squares"	=>	array(
			array(8,7),
			array(8,8),
			array(0,1),
			array(7,4),
			array(7,3),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Kai",
		"initials"	=>	"KK",
		"squares"	=>	array(
			array(4,4),
			array(0,9),
			array(2,0),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Julie",
		"initials"	=>	"JEC",
		"squares"	=>	array(
			array(4,2),
			array(6,0),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Mel",
		"initials"	=>	"MK",
		"squares"	=>	array(
			array(0,6),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Alicia",
		"initials"	=>	"AG",
		"squares"	=>	array(
			array(3,5),
			array(6,1),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Martina",
		"initials"	=>	"MP",
		"squares"	=>	array(
			array(2,2),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	array(
		"name"	=>	"Helena",
		"initials"	=>	"HE",
		"squares"	=>	array(
			array(7,1),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	
	array(
		"name"	=>	"Kristy",
		"initials"	=>	"KS",
		"squares"	=>	array(
			array(7,9),
			array(5,0),
		),
		"points"	=>	0,
		"special_points"	=>	0,
		"home_score"	=>	28,
		"away_score"	=>	24,
	),
	
);
//REVERSE SQUARES
foreach($players as $p_index => $player){
    $old_squares = $player['squares'];
    $new_squares = array();
    foreach($old_squares as $square){
        $new_squares[] = array($square[1], $square[0]);
    }
    //print_r($new_squares);
    $players[$p_index]['squares'] = $new_squares;
}
echo json_encode($players);
?>